name: Update Homebrew Casks

on:
  schedule:
    - cron: '0 0 * * 1' # every Monday at midnight
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  update-casks:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # In GitHub Actions, 'brew bump-cask-pr' requires HOMEBREW_GITHUB_API_TOKEN 
      HOMEBREW_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - run: echo "/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin" >> $GITHUB_PATH
      - uses: ./.github/actions/configure-git
      - uses: ./.github/actions/install-playwright
      # Bump casks
      - run: brew tap debugames/extras
      - run: .github/scripts/bump-cask.sh tourbox-console $(node .github/scripts/tourbox-console-version.js)
      - run: .github/scripts/bump-cask.sh xppen
      - run: .github/scripts/bump-cask.sh huion-k20
