name: Update Homebrew Casks

on:
  schedule:
    - cron: '0 0 * * 1' # every Monday at midnight
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  update-casks:
    runs-on: ubuntu-latest
    env:
      # GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # 'brew bump-cask-pr' seems to fail to authenticate with GitHub CLI (gh) on GitHub Actions.
      #  Instead of gh, specifying HOMEBREW_GITHUB_API_TOKEN works well.
      HOMEBREW_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - name: Set Homebrew's PATH
        run:  echo "/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin" >> $GITHUB_PATH
      - run: brew tap debugames/extras
      - uses: ./.github/actions/configure-git
      - uses: ./.github/actions/install-playwright
      - run: .github/scripts/bump-cask.sh tourbox-console $(node .github/scripts/get-tourbox-console-version.js)
      - run: .github/scripts/bump-cask.sh xppen
      - run: .github/scripts/bump-cask.sh huion-k20
